server:
  port: 8060
# rabbitMq配置
spring:
  rabbitmq:
    # 指定rabbitMq的地址
    host: 127.0.0.1
    # 虚拟主机name
    virtual-host: /file
    username: admin
    password: 123456
    # 新版本属性
    # simple：触发回调、waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果
    # 若发送失败则关闭channel
    # CORRELATED值是发布消息成功到交换器后会触发回调方法
    # NONE值是禁用发布确认模式，是默认值
    publisher-confirm-type: correlated
    # 队列收到消息回调
    publisher-returns: true
    # 一次拉取，拉取最大的消息量
    listener:
      simple:
        prefetch: 100
        # 手动确认
        acknowledge-mode: manual
      direct:
        prefetch: 100
        # 手动确认
        acknowledge-mode: manual
  # 设置服务名称（注册到Eureka中）
  application:
    name: file-manage
  data:
    elasticsearch:
      repositories:
        # 配置elasticsearch 配置文件
        enabled: true
# Eureka配置
eureka:
  instance:
    hostname: localhost
    # 使用ip注册
    prefer-ip-address: true
    instance-id: file-manage
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/
    # 拉取注册信息
    fetch-registry: true
    # 是否将本服务注册到eureka中
    register-with-eureka: true
